#!/usr/bin/env python3
"""Tables for POKEY PLAYER's oscilloscope -> scope.inc (HIDATA, page-aligned).

sc_sine / sc_square: 4 amplitude levels x 64 phase steps, signed bytes.
  level 0 is silence; the player indexes level*64 + phase/4.
sc_step: phase advance per sample for each note (0 = C1 ... 127). A real
  scope would show thousands of cycles; this compresses pitch so every note
  stays readable: C1 draws ~2 cycles across the 80 samples, each octave
  multiplies that by 1.41, and it tops out at 4 samples per cycle.
sc_lvl: AUDC volume 0-15 -> level 0-3.
sc_noise: drum volume 0-15 -> noise mask (the fuzz a drum hit adds).
"""
import math

PEAK = [0, 2, 3, 5]
out = ["; generated by gen_scope.py — do not edit"]


def rows(name, vals, per=16):
    out.append(f"{name}:")
    for i in range(0, len(vals), per):
        out.append("        .byte " + ",".join(f"${v & 255:02X}" for v in vals[i:i + per]))


sine, square = [], []
for p in PEAK:
    for i in range(64):
        sine.append(round(p * math.sin(2 * math.pi * i / 64)))
        square.append(p if i < 32 else -p)
rows("sc_sine", sine)
rows("sc_square", square)
rows("sc_step", [max(1, min(64, round(6 * 2 ** (n / 24)))) for n in range(128)])
rows("sc_lvl", [0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3])
rows("sc_noise", [0, 0, 1, 1, 1, 3, 3, 3, 3, 7, 7, 7, 7, 7, 7, 7])
open("scope.inc", "w").write("\n".join(out) + "\n")
print(f"scope.inc: {len(sine) + len(square) + 128 + 32} bytes")
