#!/usr/bin/env python3
"""Generate POKEY SYNTH pitch/envelope tables -> tables.inc (ca65).

Note index n = 0..95, n=0 is C1 (MIDI 24). NTSC clocks.
  lead (16-bit pair ch1+2 @ 1.79 MHz):
    pure  f = F/(2(N+7))     -> N = F/(2f) - 7
    buzz  (dist C, poly4, period 15 pulses)  f = F/(15(N+7))
    rasp  (poly5-gated pure, period 31)      f = F/(31(N+7))
    (N+7 kept coprime to the poly period, else the pattern shortens and
     the pitch jumps)
  layer (8-bit ch3 @ 64 kHz, pure): AUDF = F64/(2f) - 1, folded up an
    octave until it fits 2..255.
"""
from math import gcd

F = 1789772.5
F64 = F / 28


def freq(n):
    return 440.0 * 2 ** ((n + 24 - 69) / 12)


def lead(n, period):
    div = period if period > 2 else 2
    x = F / (div * freq(n))
    k = round(x)
    if period > 2:
        best = None
        for c in (k, k - 1, k + 1, k - 2, k + 2):
            if c >= 7 and gcd(c, period) == 1:
                if best is None or abs(c - x) < abs(best - x):
                    best = c
        k = best
    return max(0, min(0xFFFF, k - 7))


def layer(n):
    m = n
    while True:
        v = round(F64 / (2 * freq(m))) - 1
        if v <= 255:
            return max(2, v)
        m += 12


def rows(name, vals):
    out = [f"{name}:"]
    for i in range(0, len(vals), 12):
        out.append("        .byte " + ",".join(f"${v:02X}" for v in vals[i:i + 12]))
    return out


def rate(t):
    return 0x0F00 if t == 0 else min(0x0F00, round(15 * 256 / t))


ATK = [0, 1, 2, 3, 5, 7, 10, 14, 18, 24, 30, 40, 50, 64, 90, 120]
DEC = [0, 3, 5, 8, 12, 16, 22, 30, 40, 52, 66, 84, 108, 140, 180, 240]

L = ["; generated by gen_tables.py — do not edit"]
for nm, per in (("pure", 2), ("buzz", 15), ("rasp", 31)):
    v = [lead(n, per) for n in range(96)]
    L += rows(f"{nm}_lo", [x & 255 for x in v])
    L += rows(f"{nm}_hi", [x >> 8 for x in v])
L += rows("lay64", [layer(n) for n in range(96)])


def v2(n, per):
    """8-bit @64 kHz for voice 2: f = F64/(per*(AUDF+1)), AUDF+1 coprime to
    the poly period; folded up an octave while it doesn't fit."""
    m = n
    while True:
        x = F64 / (per * freq(m))
        k = round(x)
        best = None
        for c in (k, k - 1, k + 1, k - 2, k + 2):
            if c >= 2 and gcd(c, per) == 1:
                if best is None or abs(c - x) < abs(best - x):
                    best = c
        if best - 1 <= 255:
            return max(1, best - 1)
        m += 12


L += rows("buzz64", [v2(n, 15) for n in range(96)])
L += rows("rasp64", [v2(n, 31) for n in range(96)])
for nm, t in (("atk", ATK), ("dec", DEC)):
    v = [rate(x) for x in t]
    L += rows(f"{nm}_lo", [x & 255 for x in v])
    L += rows(f"{nm}_hi", [x >> 8 for x in v])
# keyboard map: KBCODE&$3F -> 0..16 note offset, $20+i drum i, $30 arrow,
# $FF = other (handled by the main thread only). GarageBand "musical typing".
KB = {'A': 0x3F, 'W': 0x2E, 'S': 0x3E, 'E': 0x2A, 'D': 0x3A, 'F': 0x38,
      'T': 0x2D, 'G': 0x3D, 'Y': 0x2B, 'H': 0x39, 'U': 0x0B, 'J': 0x01,
      'K': 0x05, 'O': 0x08, 'L': 0x00, 'P': 0x0A, ';': 0x02,
      'C': 0x12, 'V': 0x10, 'B': 0x15, 'N': 0x23, 'M': 0x25, ',': 0x20,
      '.': 0x22, '/': 0x26}
kt = [0xFF] * 64
for i, k in enumerate("AWSEDFTGYHUJKOLP;"):
    kt[KB[k]] = i
for i, k in enumerate("CVBNM,./"):
    kt[KB[k]] = 0x20 + i
for c in (0x0E, 0x0F, 0x06, 0x07):          # - = + *  (arrows w/ CTRL)
    kt[c] = 0x30
L += rows("keytype", kt)

open("tables.inc", "w").write("\n".join(L) + "\n")

# self-check: worst pitch error in cents for each table
import math
for nm, per in (("pure", 2), ("buzz", 15), ("rasp", 31)):
    worst = 0
    for n in range(96):
        N = lead(n, per)
        f = F / ((per if per > 2 else 2) * (N + 7))
        worst = max(worst, abs(1200 * math.log2(f / freq(n))))
    print(f"{nm}: worst {worst:.1f} cents")
