#!/usr/bin/env python3
"""Built-in ANTHEM song -> songdata.inc: the five sections in the demos'
compact format plus the arrangement, so the .xex plays the whole song
standalone (the Atari expands the next section into the idle lane bank and
switches at the seam, exactly as songfile.py does from the PC).

Sections carry bass (track 1) + lead (track 2) + drums; the streamed .psq
version's third voice (bar-long fifths) has no lane to live in.
"""
import contextlib
import io
import os

with contextlib.redirect_stdout(io.StringIO()):
    import compose_anthem as ca
import gen_demos as gd

S, N = ca.S, ca.N
SECTIONS = [
    ("INTRO", ca.anthem_bass(range(3)) + ca.eighths(3, "G"), [],
     ca.kit(ca.beat(kick=(0, 8), hat=(2, 6, 10, 14), bars=range(3)),
            dict(kick=[48]), ca.ROLL), "BASS", None),
    ("VERSE", ca.quarter_bass(), ca.VERSE,
     ca.kit(ca.beat(kick=(0, 8), snare=(4, 12), hat=(2, 6, 10, 14))), "BASS", "FLUTE"),
    ("CHORUS", ca.anthem_bass(), ca.HOOK, ca.CHORUS_KIT, "BASS", "ORGAN"),
    ("BREAK", [(bar * 16, ca.n(p), 16) for bar, p in
               enumerate(("A3", "F3", "C4", "G3"))], ca.BREAK,
     ca.kit(ca.beat(kick=(0,), hat=(8,), bars=range(3)), ca.ROLL), "STRINGS", "BELL"),
    ("OUTRO", ca.anthem_bass(range(3)) + [(48, ca.n("A1"), 16)], ca.OUTRO,
     ca.minus(ca.CHORUS_KIT, set(range(49, 64)))[:48] + [8] + [0] * 15,
     "BASS", "ORGAN"),
]
NAMES = [s[0] for s in SECTIONS]
ARRANGEMENT = [(n, r) for n, r in ca.ARRANGEMENT]   # ("intro", 1), ...

L = ["; generated by gen_song.py — do not edit",
     'song_name:  .byte "ANTHEM  "']
arr = []
for name, reps in ARRANGEMENT:
    arr += [NAMES.index(name.upper()) + 1, reps]
arr.append(0)                                        # end -> loops from the top
L.append("song_arr:   .byte " + ",".join(str(v) for v in arr))

size = 0
for i, (name, t1, t2, dr, p1, p2) in enumerate(SECTIONS):
    body = [S, N, gd.PRE[p1] + 1 if p1 else 0, gd.PRE[p2] + 1 if p2 else 0]
    for tr in (t1, t2):
        for t, nn, d in tr:
            body += [t, nn, d]
        body.append(0xFF)
    body += list(dr)
    size += len(body)
    L.append(f"sect{i}:      ; {name}")
    for k in range(0, len(body), 12):
        L.append("        .byte " + ",".join(str(v) for v in body[k:k + 12]))
L.append("sect_lo:    .byte " + ",".join(f"<sect{i}" for i in range(len(SECTIONS))))
L.append("sect_hi:    .byte " + ",".join(f">sect{i}" for i in range(len(SECTIONS))))
L.append(f"NSECT = {len(SECTIONS)}")
open("songdata.inc", "w").write("\n".join(L) + "\n")
frames = sum(N * S * r for _, r in ARRANGEMENT)
print(f"{len(SECTIONS)} sections, {size} bytes of pattern data + "
      f"{len(arr)} arrangement bytes; song = {frames} frames ({frames / 59.92:.0f} s)")
