#!/usr/bin/env python3
"""Slice the sound engine out of synth.s -> engine.inc, so the standalone
player shares the synth's code instead of a copy that would drift.

Takes the equates (page-6 and hardware addresses) plus the routines listed
in ROUTINES, each from its label to the next top-level label. If a routine
is renamed or moved, this fails loudly instead of silently emitting junk.
"""
import re
import sys

ROUTINES = [
    # lead voice + helpers
    "laytune", "synth", "coprime", "note_play", "note_stop", "note_start",
    "poly_out", "poly_pitch",
    # loop voices (the player's 2nd and 3rd voices)
    "lv_load", "lv_on", "lv_off", "v2_owns", "lv_step", "lv_tones", "lv_pitch",
    # drums
    "drum_trig", "drum_start", "drum_step", "drum_one",
    # output + stereo
    "pokey_out", "detect_stereo",
]
# the tables those routines index (chord shapes, drum kit, presets)
DATA = ["wavebits", "chord_start", "chord_len", "chord_ofs", "layofs", "swsh",
        "vibtab", "octbase", "dr_frq", "dr_dlt", "dr_ctl", "dr_vsh", "dr_clk",
        "dr_seq", "dr_len", "drseq", "bad15", "pbase", "factory"]
SKIP_EQU = {"SCMDN", "NDEMO"}


def slice_routines(src):
    lines = src.split("\n")
    starts = {}
    for i, ln in enumerate(lines):
        m = re.match(r"^([a-z_][a-z_0-9]*):", ln)
        if m and m.group(1) not in starts:
            starts[m.group(1)] = i
    tops = sorted(starts.values())
    out = []
    for name in ROUTINES:
        if name not in starts:
            sys.exit(f"gen_engine: routine '{name}' not found in synth.s")
        i = starts[name]
        j = next((t for t in tops if t > i), len(lines))
        # keep any comment block directly above the label
        k = i
        while k > 0 and lines[k - 1].lstrip().startswith(";"):
            k -= 1
        out.append("\n".join(lines[k:j]).rstrip())
    return "\n\n".join(out)


def slice_data(src):
    lines = src.split("\n")
    out = []
    for name in DATA:
        i = next((k for k, ln in enumerate(lines)
                  if re.match(rf"^{name}:", ln)), None)
        if i is None:
            sys.exit(f"gen_engine: table '{name}' not found in synth.s")
        j = i + 1
        while j < len(lines) and (lines[j].startswith((" ", "\t"))
                                  and lines[j].strip()):
            j += 1
        out.append("\n".join(lines[i:j]).rstrip())
    return "\n".join(out)


def equates(src):
    out = []
    for ln in src.split("\n"):
        m = re.match(r"^([A-Z_][A-Z_0-9]*)\s*=\s*(\S+)", ln)
        if m and m.group(1) not in SKIP_EQU:
            out.append(ln.rstrip())
    return "\n".join(out)


src = open("synth.s").read()
body = f"""; generated by gen_engine.py from synth.s — do not edit
; The standalone player (player.s) shares the synth's sound engine through
; this file: same voices, same presets, same stereo handling.

{equates(src)}

{slice_routines(src)}

; ---- the tables the engine indexes -----------------------------------------
{slice_data(src)}

.segment "DATA"
live:   .res 10*PSTRIDE          ; presets, editable at runtime by the synth
.segment "CODE"
"""
open("engine.inc", "w").write(body)
print(f"engine.inc: {len(body.split(chr(10)))} lines, "
      f"{len(ROUTINES)} routines + equates")
